apiVersion: v1
kind: Secret
metadata:
  name: fashion-crm-secrets
type: Opaque
data:
  DASHSCOPE_API_KEY: ${DASHSCOPE_API_KEY_BASE64}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashion-crm-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fashion-crm-backend
  template:
    metadata:
      labels:
        app: fashion-crm-backend
    spec:
      containers:
      - name: backend
        image: ${ACR_REGISTRY}/fashion-crm-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DASHSCOPE_API_KEY
          valueFrom:
            secretKeyRef:
              name: fashion-crm-secrets
              key: DASHSCOPE_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashion-crm-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fashion-crm-frontend
  template:
    metadata:
      labels:
        app: fashion-crm-frontend
    spec:
      containers:
      - name: frontend
        image: ${ACR_REGISTRY}/fashion-crm-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_BASE_URL
          value: "https://api.fashion-crm.com"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: fashion-crm-backend
spec:
  selector:
    app: fashion-crm-backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fashion-crm-frontend
spec:
  selector:
    app: fashion-crm-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
